AWSTemplateFormatVersion: '2024-08-24'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 3 API - com.example.lambda::springboot-aws-lambda-example
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  AwsLambdaExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.example.lambda.StreamLambdaHandler::handleRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  AwsLambdaExampleApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/dev/ready'
    Export:
      Name: AwsLambdaExampleApi
